src/MeetupApi.MvcApp/Controllers/EventController.cs
using MeetupApi.Infrastructure;
using MeetupApi.MvcApp.Utility.HttpClients;
using MeetupApi.MvcApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MeetupApi.MvcApp.Controllers
{
    public class EventController : Controller
    {
        private readonly ServiceApiClient _serviceApiClient;
        
        public EventController(ServiceApiClient serviceApiClient)
        {
            _serviceApiClient = serviceApiClient;
        }

        public async Task<ActionResult> Index()
        {
            IEnumerable<EventViewModel>? model = null;
            using (var result = await _serviceApiClient.Client.GetAsync(String.Empty))
            {
                if (result.IsSuccessStatusCode)
                {
                    var readTask = await result.Content.ReadAsAsync<IList<EventViewModel>>();
                    model = readTask;
                }
                else
                {
                    return BadRequest();
                }
            }
            return View("Index", model);
        }

        public async Task<ActionResult> Delete(int id)
        {
            return await GetById(id);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            using (var result = await _serviceApiClient.Client.DeleteAsync($"{id}"))
            {
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                else return NotFound();
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EventDto eventDto)
        {
            if (ModelState.IsValid)
            {
                using (var result = await _serviceApiClient.Client.PostAsJsonAsync(String.Empty, eventDto))
                {
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return Ok();
        }

        // GET: HomeController1/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return await GetById(id);
        }

        // POST: HomeController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(int id, EventDto eventDto)
        {
            if (id != eventDto.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                using (var result = await _serviceApiClient.Client.PutAsJsonAsync($"{id}", eventDto))
                {
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return View(eventDto);
        }

        public async Task<ActionResult> GetById(int id)
        {
            EventViewModel? model = null;
            using (var result = await _serviceApiClient.Client.GetAsync($"{id}"))
            {
                if (result.IsSuccessStatusCode)
                {
                    var readTask = await result.Content.ReadAsAsync<EventViewModel>();
                    model = readTask;
                }
                else
                {
                    return NotFound();
                }
            }
            return View(model);
        }
    }
}

src/MeetupApi.MvcApp/Controllers/UserEventsController.cs
using MeetupApi.Infrastructure;
using MeetupApi.MvcApp.Utility;
using MeetupApi.MvcApp.Utility.HttpClients;
using MeetupApi.MvcApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MeetupApi.MvcApp.Controllers
{
    public class UserEventsController : Controller
    {
        private readonly ServiceApiClient _serviceApiClient;

        public UserEventsController(ServiceApiClient serviceApiClient)
        {
            _serviceApiClient = serviceApiClient;
        }

        public async Task<IActionResult> Index()
        {
            string? userId = HttpContext.Request.Cookies[CookiesKeys.UserId];
            if (string.IsNullOrEmpty(userId)) userId = "null";

            IEnumerable<EventViewModel>? model = null;
            using (var result = await _serviceApiClient.Client.GetAsync("all/special/" + userId))
            {
                if (result.IsSuccessStatusCode)
                {
                    var readTask = await result.Content.ReadAsAsync<IList<EventViewModel>>();
                    model = readTask;
                }
                if(model == null) return NotFound();
            }
            return View("Index", model);
        }

        public async Task<ActionResult> Details(int id)
        {
            return await GetById(id);
        }

        public async Task<ActionResult> GetById(int id)
        {
            EventViewModel? model = null;
            using (var result = await _serviceApiClient.Client.GetAsync($"{id}"))
            {
                if (result.IsSuccessStatusCode)
                {
                    var readTask = await result.Content.ReadAsAsync<EventViewModel>();
                    model = readTask;
                }
                else
                {
                    return NotFound();
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Unsubscribe(int id)
        {
            string? userId;
            string? userRole;

            if (IsUser(out userId, out userRole))
            {
                UserSubscription userSub = new UserSubscription { UserId = userId! };
                using (var result = await _serviceApiClient.Client.PostAsJsonAsync("unsubscribe/" + $"{id}", userSub))
                {
                    if (result.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else return BadRequest();
                }
            }
            return Ok();
        }

        [NonAction]
        private bool IsUser(out string userId, out string userRole)
        {
            bool isAuth = Convert.ToBoolean(HttpContext.Request.Cookies[CookiesKeys.IsAuthenticated]);
            userRole = HttpContext.Request.Cookies[CookiesKeys.UserRole];
            userId = HttpContext.Request.Cookies[CookiesKeys.UserId];
            if (isAuth & userRole == "User") return true;
            return false;
        }
    }
}

src/MeetupApi.MvcApp/Views/Shared/_Layout.cshtml
@using MeetupApi.MvcApp.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeetupApi.MvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeetupApi.MvcApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MeetupApi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Events</a>
                        </li>
                        @if (Convert.ToBoolean(Context.Request.Cookies[CookiesKeys.IsAuthenticated]) & Context.Request.Cookies[CookiesKeys.UserRole] == "Admin")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index">Admin page</a>
                            </li>
                        }
                        else if (Convert.ToBoolean(Context.Request.Cookies[CookiesKeys.IsAuthenticated]) & Context.Request.Cookies[CookiesKeys.UserRole] == "User")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserEvents" asp-action="Index">My Events</a>
                        </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MeetupApi.MvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>